enable-magisk-update = true
parallel-jobs = 1

[SoundCloud]
build-mode = "module"
included-patches = "'Hide ads' 'Enable offline sync'"
patcher-args = "-e 'Spoof SIM country' -OnetworkIsoCountryCode=DE -OsimIsoCountryCode=DE -e 'Disable telemetry'"
arch = "both"
version = "auto"
uptodown-dlurl = "https://soundcloud.en.uptodown.com/android"

